{% set name = "mlpack" %}
{% set version = "3.3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlpack/mlpack/archive/master.tar.gz
  sha256: 5331e60fa47a2809ed3680d17752670713d9ff19e4824b6b3af1e16a2bac5915

build:
  number: 1
  skip: true  # [win or osx]

requirements:
  build:
    - pkg-config
    - cmake
    - make
    - cotire
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - setuptools
    - python
    - boost >=1.69.0
    - numpy
    - pandas  >=0.15.0
    - armadillo >=6.500.0
    - pytest-runner
    - openblas
    - ensmallen >=2.12.1.1
    - libcblas
    - libblas
  run:
    - python
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - pandas  >=0.15.0
    - armadillo >=6.500.0
    - openblas
    - {{ pin_compatible('numpy') }}
    - ensmallen >=2.12.1.1
about:
  home: http://www.mlpack.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: mlpack a fast, flexible machine learning library
  description: |
    mlpack is an intuitive, fast, and flexible C++ machine learning library
    with bindings to other languages. It is meant to be a machine learning analog
    to LAPACK, and aims to implement a wide array of machine learning methods and
    functions as a "swiss army knife" for machine learning researchers. In addition
    to its powerful C++ interface, mlpack also provides command-line programs and
    Python bindings.
  doc_url: http://www.mlpack.org/docs.html
  dev_url: https://github.com/mlpack/mlpack

extra:
  recipe-maintainers:
    - zoq
